# Generated by Django 5.1.3 on 2024-11-09 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_question_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
