# Generated by Django 5.1.3 on 2024-11-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_delete_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='images_answer/'),
        ),
    ]
